const express=require("express")
const userRouter=require("./userRouter")
const partnerRouter=require("./partnerRouter")
const contactRouter=require("./contactRouter")
const serviceRouter=require("./serviceRouter")
const mainRouter=express()
mainRouter.use("/user",userRouter)
mainRouter.use("/partner",partnerRouter)
mainRouter.use("/contact",contactRouter)
mainRouter.use("/service",serviceRouter)
module.exports=mainRouter