const express =require("express")
const partnermodel=require("../model/partnerSchema")
const Otppartner=require("../model/Otppartner")
const partnerController=require("../controller/partnerController")
const {partnervalidate,partnervalidation,verifytoken}=require("../middleware/partner")
const partnerRouter=express()
partnerRouter.post("/adding",partnervalidate,partnerController.newpartner)
partnerRouter.get("/listing",verifytoken,partnerController.partnerlist)
partnerRouter.post("/partnerlogin",partnerController.partnerLogin)
partnerRouter.post("/OtpGenerating",partnerController.Otpemail)
partnerRouter.post("/Changedpassword",partnervalidation,partnerController.ChangePassword)
partnerRouter.post("/partnermail",partnerController.partnermailer)
module.exports=partnerRouter